// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc_model

type Seen struct {
	Project string
	Type    string
	Value   string
}

type Url struct {
	Project   string
	ID        string
	Value     string
	Via       string
	Host      string
	Path      string
	Type      string
	Crawler   string
	Status    string
	LiftOff   int64
	Timestamp int64
}
