// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc_model

type Seen struct {
	Project   string
	Type      string
	Value     string
	Timestamp int64
}

type Url struct {
	Project   string
	ID        string
	Value     string
	Via       string
	Host      string
	Path      string
	Type      string
	Crawler   string
	Status    string
	Timestamp int64
}
